const gottheit = [
    {"name":"Abbathor","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":", zwergischer Gott der Habgier"},
    {"name":"Aerdrie Faenya","genus":"femininum","numerus":"singular","adjektiv":"","präfix":"","suffix":", elfische Göttin des Himmels"},
    {"name":"Akadi","genus":"femininum","numerus":"singular","adjektiv":"","präfix":"","suffix":", Göttin der Luft"},
    {"name":"Alathrien Druanna","genus":"femininum","numerus":"singular","adjektiv":"","präfix":"","suffix":", elfische Göttin der Runen, des Schreibens und des Zauberns"},
    {"name":"Alobal Lorfiril","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":", elfischer Gott der Ausgelassenheit und der Fröhlichkeit"},
    {"name":"Amaunator","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":", Gott der Sonne"},
    {"name":"Angharradh","genus":"femininum","numerus":"singular","adjektiv":"","präfix":"","suffix":", elfische Göttin der Weisheit und des Schutzes"},
    {"name":"Araleth Letheranil","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":", elfischer Gott des Lichts, der Sterne und der Offenbarung"},
    {"name":"Arvoreen","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":", halblingischer Gott der Wachsamkeit und des Krieges"},
    {"name":"Asmodeus","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":", Gott des Genusses"},
    {"name":"Auril","genus":"femininum","numerus":"singular","adjektiv":"","präfix":"","suffix":", Göttin des Winters"},
    {"name":"Azuth","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":", Gott der Magie"},
    {"name":"Baervan Wildwanderer","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":", gnomischer Gott der Wälder"},
    {"name":"Bahgtru","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":", orkischer Gott der Stärke"},
    {"name":"Tyrannos","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":", Gott der Tyrannei"},
    {"name":"Baravar Mantelschatten","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":", gnomischer Gott der Illusion und der Täuschung"},
    {"name":"Berronar Wahrsilber","genus":"femininum","numerus":"singular","adjektiv":"","präfix":"","suffix":", zwergische Göttin von Herd und Heimat"},
    {"name":"Beshaba","genus":"femininum","numerus":"singular","adjektiv":"","präfix":"","suffix":", Göttin des Unglücks"},
    {"name":"Bhaal","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":", Gott des Mordes"},
    {"name":"Bleredd","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":", Gott der Arbeit und des Handwerks"},
    {"name":"Brandobaris","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":", halblingischer Gott des Diebstahls und der Abenteuer"},
    {"name":"Callarduran Sanfthände","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":", gnomischer Gott des Bergbaus und der Steinbearbeitung"},
    {"name":"Charmalaine","genus":"femininum","numerus":"singular","adjektiv":"","präfix":"","suffix":", halblingische Göttin der scharfen Sinne und des Glücks"},
    {"name":"Chauntea","genus":"femininum","numerus":"singular","adjektiv":"","präfix":"","suffix":", Göttin der Landwirtschaft"},
    {"name":"Corellon Larethian","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":", elfischer Gott der Kunst und der Magie"},
    {"name":"Cyric","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":", Gott der Lügen"},
    {"name":"Cyrrollalee","genus":"femininum","numerus":"singular","adjektiv":"","präfix":"","suffix":", halblingische Göttin von Herd und Heimat"},
    {"name":"Darahl Tilvenar","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":", elfischer Gott des Feuers, der Erde und der Metallarbeit"},
    {"name":"Deneir","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":", Gott der Schrift"},
    {"name":"Ritterin","genus":"femininum","numerus":"singular","adjektiv":"rote","präfix":"","suffix":", Göttin der Strategie"},
    {"name":"Dugmaren Leuchtmantel","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":", zwergischer Gott der Entdeckung"},
    {"name":"Dumathoin","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":", zwergischer Gott der begrabenen Geheimnisse"},
    {"name":"Eilistraee","genus":"femininum","numerus":"singular","adjektiv":"","präfix":"","suffix":", Drow-Göttin der Lieder und des Mondlichts"},
    {"name":"Eldath","genus":"femininum","numerus":"singular","adjektiv":"","präfix":"","suffix":", Göttin des Friedens"},
    {"name":"Elebrin Liothiel","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":", elfischer Gott der Fülle, der Gärten und der Ernte"},
    {"name":"Erevan Ilesere","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":", elfischer Gott des Unfugs"},
    {"name":"Fenmarel Mestarine","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":", elfischer Gott der Ausgestoßenen"},
    {"name":"Flandal Stahlhaut","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":", gnomischer Gott der Metallarbeit"},
    {"name":"Gadhelyn","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":", elfischer Gott der Unabhängigkeit und der Ächtung"},
    {"name":"Gaerdal Eisenhand","genus":"femininum","numerus":"singular","adjektiv":"","präfix":"","suffix":", gnomische Göttin des Schutzes"},
    {"name":"Garl Glitzergold","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":", gnomischer Gott der List und der Juwelen"},
    {"name":"Gelf Dunkelherd","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":", gnomischer Gott der Frustration und der Zerstörung"},
    {"name":"Ghaunadaur","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":", Drow-Gott der Schlicke, des Schleims und der Ausgestoßenen"},
    {"name":"Gond","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":", Gott des Handwerks"},
    {"name":"Gorm Gulthyn","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":", zwergischer Gott der Wachsamkeit"},
    {"name":"Grumbar","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":", Gott der Erde"},
    {"name":"Gwaeron Windstrom","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":", Gott des Spurenlesens"},
    {"name":"Haela Leuchtaxt","genus":"femininum","numerus":"singular","adjektiv":"","präfix":"","suffix":", zwergische Göttin des Schlachtenglücks"},
    {"name":"Hanali Celanil","genus":"femininum","numerus":"singular","adjektiv":"","präfix":"","suffix":", elfische Göttin der Liebe und der Schönheit"},
    {"name":"Hanseath","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":", zwergischer Gott der Festlichkeiten, des Brauens und der Lieder"},
    {"name":"Helm","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":", Gott des Schutzes"},
    {"name":"Hoar","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":", Gott der Rache und der Bestrafung"},
    {"name":"Ilmater","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":", Gott der Ausdauer"},
    {"name":"Istishia","genus":"femininum","numerus":"singular","adjektiv":"","präfix":"","suffix":", Göttin des Wassers"},
    {"name":"Jergal","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":", Schreiber der Toten"},
    {"name":"Kelemvor","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":", Gott der Toten"},
    {"name":"Keptolo","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":", Drow-Gott der Schönheit, der Lebenskunst und der Fruchtbarkeit"},
    {"name":"Kiaransalee","genus":"femininum","numerus":"singular","adjektiv":"","präfix":"","suffix":", Drow-Göttin der Nekromantie"},
    {"name":"Kirith Sotheril","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":", elfischer Gott der Erkenntnis und der Illusion"},
    {"name":"Clangeddin Silberbart","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":", zwergischer Gott des Krieges und der Strategie"},
    {"name":"Kossuth","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":", Gott des Feuers"},
    {"name":"Labelas Enoreth","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":", elfischer Gott der Zeit, der Geschichte und der Philosophie"},
    {"name":"Laduguer","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":", Duergar-Gott der Magie und der Sklaverei"},
    {"name":"Lathander","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":", Gott der Morgendämmerung und Erneuerung"},
    {"name":"Leira","genus":"femininum","numerus":"singular","adjektiv":"","präfix":"","suffix":", Göttin der Illusion"},
    {"name":"Lliira","genus":"femininum","numerus":"singular","adjektiv":"","präfix":"","suffix":", Göttin der Freude"},
    {"name":"Lolth","genus":"femininum","numerus":"singular","adjektiv":"","präfix":"","suffix":", Göttin der Spinnen"},
    {"name":"Loviatar","genus":"femininum","numerus":"singular","adjektiv":"","präfix":"","suffix":", Göttin der Schmerzen"},
    {"name":"Luthic","genus":"femininum","numerus":"singular","adjektiv":"","präfix":"","suffix":", orkische Muttergöttin der Fruchtbarkeit und der Heilung"},
    {"name":"Malar","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":", Gott der Jagd"},
    {"name":"Malyk","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":", Drow-Gott des Chaos, der Rebellion und der wilden Magie"},
    {"name":"Marthammor Duin","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":", zwergischer Gott der Wanderer"},
    {"name":"Mask","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":", Gott der Diebe"},
    {"name":"Melira Taralen","genus":"femininum","numerus":"singular","adjektiv":"","präfix":"","suffix":", elfische Göttin der Poesie und der Lieder"},
    {"name":"Mielikki","genus":"femininum","numerus":"singular","adjektiv":"","präfix":"","suffix":", Göttin der Wälder"},
    {"name":"Milil","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":", Gott der Dichtung und der Lieder"},
    {"name":"Moradin","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":", zwergischer Gott der Schöpfung"},
    {"name":"Muamman Duathal","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":", zwergischer Gott der Stürme und der Reisen"},
    {"name":"Mya","genus":"femininum","numerus":"singular","adjektiv":"","präfix":"","suffix":", zwergische Göttin der Klane, der Familie und der Weisheit"},
    {"name":"Myrkul","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":", Gott des Todes"},
    {"name":"Mystra","genus":"femininum","numerus":"singular","adjektiv":"","präfix":"","suffix":", Göttin der Magie"},
    {"name":"Mythrien Sarath","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":", elfischer Gott der Entsagung und der Mythale"},
    {"name":"Naralis Analor","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":", elfischer Gott der Heilung, des Leidens und des Todes"},
    {"name":"Nebelun","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":", gnomischer Gott der Erfindung und des Glücks"},
    {"name":"Oghma","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":", Gott des Wissens"},
    {"name":"Rellavar Danuvien","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":", elfischer Gott des Winters und des rauen Wetters"},
    {"name":"Rill Schlaudrossel","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":", gnomischer Gott der Gesetze und der Gedanken"},
    {"name":"Rillifane Rallathil","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":", elfischer Gott der Natur"},
    {"name":"Roknar","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":", zwergischer Gott der Lügen und Intrigen"},
    {"name":"Sarula Iliene","genus":"femininum","numerus":"singular","adjektiv":"","präfix":"","suffix":", elfische Göttin der Seen und der Ströme"},
    {"name":"Savras","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":", Gott der Weissagung und des Schicksals"},
    {"name":"Segojan Erdrufer","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":", gnomischer Gott der Erde und der Toten"},
    {"name":"Sehanine Mondbogen","genus":"femininum","numerus":"singular","adjektiv":"","präfix":"","suffix":", elfische Göttin der Weissagung, der Träume, des Todes und der Reise"},
    {"name":"Selûne","genus":"femininum","numerus":"singular","adjektiv":"","präfix":"","suffix":", Göttin des Mondes"},
    {"name":"Selvetarm","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":", Drow-Gott der Krieger"},
    {"name":"Shar","genus":"femininum","numerus":"singular","adjektiv":"","präfix":"","suffix":", Göttin der Dunkelheit und des Verlustes"},
    {"name":"Shargaas","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":", orkischer Gott der Heimlichkeit und der Dunkelheit"},
    {"name":"Sharindlar","genus":"femininum","numerus":"singular","adjektiv":"","präfix":"","suffix":", zwergische Göttin der Heilung und der Liebe"},
    {"name":"Sheela Peryroyl","genus":"femininum","numerus":"singular","adjektiv":"","präfix":"","suffix":", halblingische Göttin der Landwirtschaft und des Wetters"},
    {"name":"Shevaresh","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":", elfischer Gott der Rache"},
    {"name":"Sheyanna Flachssträhne","genus":"femininum","numerus":"singular","adjektiv":"","präfix":"","suffix":", Göttin der Liebe, der Schönheit und der Leidenschaft"},
    {"name":"Silvanus","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":", Gott der Wilden Natur"},
    {"name":"Solonor Thelandira","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":", elfischer Gott des Bogenschießens"},
    {"name":"Sune","genus":"femininum","numerus":"singular","adjektiv":"","präfix":"","suffix":", Göttin der Liebe und der Schönheit"},
    {"name":"Talona","genus":"femininum","numerus":"singular","adjektiv":"","präfix":"","suffix":", Göttin von Gift und Krankheit"},
    {"name":"Talos","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":", Gott der Stürme"},
    {"name":"Tarsellis Meunniduin","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":", elfischer Gott der Berge, der Flüsse und der wilden Orte"},
    {"name":"Tempus","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":", Gott des Krieges"},
    {"name":"Tethrin Veraldé","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":", elfischer Gott des Kampfes und des Schwertkampfes"},
    {"name":"Thard Harr","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":", zwergischer Gott der Wildnis und der Jagd"},
    {"name":"Tharmekhûl","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":", zwergischer Gott des Feuers, des Schmiedens und des geschmolzenen Gesteins"},
    {"name":"Thautam","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":", zwergischer Gott der Geheimnisse, der Dunkelheit und der verlorenen Schätze"},
    {"name":"Duerra","genus":"femininum","numerus":"singular","adjektiv":"","präfix":"Tiefe","suffix":", Duergar-Göttin der Eroberung und der Psionik"},
    {"name":"Sashelas","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"Tiefe","suffix":", elfischer Gott des Meeres"},
    {"name":"Torm","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":", Gott der Tapferkeit und Selbstaufopferung"},
    {"name":"Tymora","genus":"femininum","numerus":"singular","adjektiv":"","präfix":"","suffix":", Göttin des Glücks"},
    {"name":"Tyr","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":", Gott der Gerechtigkeit"},
    {"name":"Ulaa","genus":"femininum","numerus":"singular","adjektiv":"","präfix":"","suffix":", zwergische Göttin des Bergbaus und der Steinbrüche"},
    {"name":"Umberlee","genus":"femininum","numerus":"singular","adjektiv":"","präfix":"","suffix":", Göttin des Meeres"},
    {"name":"Urdlen","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":", gnomischer Gott der Gier und des Mordes"},
    {"name":"Urogalan","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":", halblingischer Gott der Erde und des Todes"},
    {"name":"Valkauna","genus":"femininum","numerus":"singular","adjektiv":"","präfix":"","suffix":", zwergische Göttin der Schwüre, der Geburt, der Alterung und des Todes"},
    {"name":"Valkur","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":", nordländischer Gott der Seeleute"},
    {"name":"Vandria Gilmadrith","genus":"femininum","numerus":"singular","adjektiv":"","präfix":"","suffix":", elfische Göttin des Krieges, des Kummers, der Gerechtigkeit und der Wachsamkeit"},
    {"name":"Vergadain","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":", zwergischer Gott des Glücks und des Wohlstands"},
    {"name":"Vhaeraun","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":", Drow-Gott der Diebe"},
    {"name":"Waukeen","genus":"femininum","numerus":"singular","adjektiv":"","präfix":"","suffix":", Göttin des Handelns"},
    {"name":"Ye'Cind","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":", elfischer Gott der Musik und der Verzauberung"},
    {"name":"Yondalla","genus":"femininum","numerus":"singular","adjektiv":"","präfix":"","suffix":", halblingische Göttin der Fruchtbarkeit und des Schutzes"},
    {"name":"Yurtrus","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":", orkischer Gott des Todes und der Krankheit"},
    {"name":"Zandilar","genus":"femininum","numerus":"singular","adjektiv":"","präfix":"","suffix":", elfische Göttin der Romantik, der Begierde und des Tanzes"},
    {"name":"Zinzerena","genus":"femininum","numerus":"singular","adjektiv":"","präfix":"","suffix":", Drow-Göttin des Mordes, der Illusion und der Lügen"},
    {"name":"Gruumsh","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":", orkischer Gott der Stürme und des Krieges"},
    {"name":"Ilneval","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":", orkischer Gott der Strategie und der Horden"}
   ];
  
   const gottheitData = getRandomText(gottheit);
   const gottheitName = gottheitData.name;
   const gottheitGeschlecht = gottheitData.genus;
   const gottheitAnzahl = gottheitData.numerus;
   const gottheitAdjektiv = gottheitData.adjektiv;
   const gottheitPräfix = gottheitData.präfix;
   const gottheitSuffix = gottheitData.suffix;