const kleidungsstückePlural = [
    {"name":"Armschützer","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Badeanzüge","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Balaclavas","genus":"neutrum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Beckenhauben","genus":"femininum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Beinkleider","genus":"neutrum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Beinschienen","genus":"femininum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Beinwickel","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Beutel","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Boleros","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Brustpanzer","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Brustplatten","genus":"femininum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Buchsen","genus":"femininum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Bunthauben","genus":"femininum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Büstenhalter","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Ellenbogenpanzer","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Faltröcke","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Fausthandschuhe","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Fäustlinge","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Gambesons","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Geschlechtsteil-Schutze","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Gewänder","genus":"neutrum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Gürtel","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Handschuhe","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Hauberke","genus":"neutrum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Helme","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Helmbüsche","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Hemden","genus":"neutrum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Hosen","genus":"femininum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Hüftschutze","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Hüte","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Kappen","genus":"femininum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Kehlkopfschutze","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Kilts","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Kleider","genus":"neutrum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Knieschoner","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Korsette","genus":"neutrum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Krawatten","genus":"femininum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Jacken","genus":"femininum","numerus":"plural","adjektiv":"kurze","präfix":"","suffix":""},
    {"name":"Kutten","genus":"femininum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Jacken","genus":"femininum","numerus":"plural","adjektiv":"lange","präfix":"","suffix":""},
    {"name":"Stiefel","genus":"maskulinum","numerus":"plural","adjektiv":"lange","präfix":"","suffix":""},
    {"name":"Lendenschurze","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Leotards","genus":"neutrum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Mäntel","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Masken","genus":"femininum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Jacken","genus":"femininum","numerus":"plural","adjektiv":"mittellange","präfix":"","suffix":""},
    {"name":"Morgenmäntel","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Oberschenkelschutze","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Overalls","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Parkas","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Pelerinen","genus":"femininum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Ponchos","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Pullover","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Roben","genus":"femininum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Schals","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Schleppen","genus":"femininum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Schlipse","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Schuhe","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Schulterpanzer","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Schulterstücke","genus":"neutrum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Schürzen","genus":"femininum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Socken","genus":"femininum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Stiefel","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Stirnbänder","genus":"neutrum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Strickjacken","genus":"femininum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Strumpfhosen","genus":"femininum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Togas","genus":"femininum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Topfhelme","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Trenchcoats","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Tücher","genus":"neutrum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Tuniken","genus":"femininum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Umhänge","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Unterarmschutze","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Unterröcke","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Wämser","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Westen","genus":"femininum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Zwangsjacken","genus":"femininum","numerus":"plural","adjektiv":"","präfix":"","suffix":""}
   ];
   
   const kleidungsstückePluralData = getRandomText(kleidungsstückePlural);
   const kleidungsstückePluralName = kleidungsstückePluralData.name;
   const kleidungsstückePluralGeschlecht = kleidungsstückePluralData.genus;
   const kleidungsstückePluralAnzahl = kleidungsstückePluralData.numerus;
   const kleidungsstückePluralAdjektiv = kleidungsstückePluralData.adjektiv;
   const kleidungsstückePluralPräfix = kleidungsstückePluralData.präfix;
   const kleidungsstückePluralSuffix = kleidungsstückePluralData.suffix;