const kleidungsstückeSingular = [
    {"name":"Armschutz","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":""},
    {"name":"Badeanzug","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":""},
    {"name":"Balaclava","genus":"neutrum","numerus":"singular","adjektiv":"","präfix":"","suffix":""},
    {"name":"Beckenhaube","genus":"femininum","numerus":"singular","adjektiv":"","präfix":"","suffix":""},
    {"name":"Beinkleid","genus":"neutrum","numerus":"singular","adjektiv":"","präfix":"","suffix":""},
    {"name":"Beinschiene","genus":"femininum","numerus":"singular","adjektiv":"","präfix":"","suffix":""},
    {"name":"Beinwickel","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":""},
    {"name":"Beutel","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":""},
    {"name":"Bolero","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":""},
    {"name":"Brustpanzer","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":""},
    {"name":"Brustplatte","genus":"femininum","numerus":"singular","adjektiv":"","präfix":"","suffix":""},
    {"name":"Buchse","genus":"femininum","numerus":"singular","adjektiv":"","präfix":"","suffix":""},
    {"name":"Bunthaube","genus":"femininum","numerus":"singular","adjektiv":"","präfix":"","suffix":""},
    {"name":"Büstenhalter","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":""},
    {"name":"Ellenbogenpanzer","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":""},
    {"name":"Faltrock","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":""},
    {"name":"Fausthandschuh","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":""},
    {"name":"Fäustling","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":""},
    {"name":"Gambeson","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":""},
    {"name":"Geschlechtsteil-Schutz","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":""},
    {"name":"Gewand","genus":"neutrum","numerus":"singular","adjektiv":"","präfix":"","suffix":""},
    {"name":"Gürtel","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":""},
    {"name":"Handschuh","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":""},
    {"name":"Hauberk","genus":"neutrum","numerus":"singular","adjektiv":"","präfix":"","suffix":""},
    {"name":"Helm","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":""},
    {"name":"Helmbusch","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":""},
    {"name":"Hemd","genus":"neutrum","numerus":"singular","adjektiv":"","präfix":"","suffix":""},
    {"name":"Hose","genus":"femininum","numerus":"singular","adjektiv":"","präfix":"","suffix":""},
    {"name":"Hüftschutz","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":""},
    {"name":"Hut","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":""},
    {"name":"Kappe","genus":"femininum","numerus":"singular","adjektiv":"","präfix":"","suffix":""},
    {"name":"Kehlkopfschutz","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":""},
    {"name":"Kilt","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":""},
    {"name":"Kleid","genus":"neutrum","numerus":"singular","adjektiv":"","präfix":"","suffix":""},
    {"name":"Knieschoner","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":""},
    {"name":"Korsett","genus":"neutrum","numerus":"singular","adjektiv":"","präfix":"","suffix":""},
    {"name":"Krawatte","genus":"femininum","numerus":"singular","adjektiv":"","präfix":"","suffix":""},
    {"name":"Jacke","genus":"femininum","numerus":"singular","adjektiv":"kurze","präfix":"","suffix":""},
    {"name":"Kutte","genus":"femininum","numerus":"singular","adjektiv":"","präfix":"","suffix":""},
    {"name":"Jacke","genus":"femininum","numerus":"singular","adjektiv":"lange","präfix":"","suffix":""},
    {"name":"Stiefel","genus":"maskulinum","numerus":"singular","adjektiv":"lange","präfix":"","suffix":""},
    {"name":"Lendenschurz","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":""},
    {"name":"Leotard","genus":"neutrum","numerus":"singular","adjektiv":"","präfix":"","suffix":""},
    {"name":"Mantel","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":""},
    {"name":"Maske","genus":"femininum","numerus":"singular","adjektiv":"","präfix":"","suffix":""},
    {"name":"Jacke","genus":"femininum","numerus":"singular","adjektiv":"mittellange","präfix":"","suffix":""},
    {"name":"Morgenmantel","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":""},
    {"name":"Oberschenkelschutz","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":""},
    {"name":"Overall","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":""},
    {"name":"Parka","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":""},
    {"name":"Pelerine","genus":"femininum","numerus":"singular","adjektiv":"","präfix":"","suffix":""},
    {"name":"Poncho","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":""},
    {"name":"Pullover","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":""},
    {"name":"Robe","genus":"femininum","numerus":"singular","adjektiv":"","präfix":"","suffix":""},
    {"name":"Schal","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":""},
    {"name":"Schleppe","genus":"femininum","numerus":"singular","adjektiv":"","präfix":"","suffix":""},
    {"name":"Schlips","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":""},
    {"name":"Schuh","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":""},
    {"name":"Schulterpanzer","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":""},
    {"name":"Schulterstück","genus":"neutrum","numerus":"singular","adjektiv":"","präfix":"","suffix":""},
    {"name":"Schürze","genus":"femininum","numerus":"singular","adjektiv":"","präfix":"","suffix":""},
    {"name":"Socke","genus":"femininum","numerus":"singular","adjektiv":"","präfix":"","suffix":""},
    {"name":"Stiefel","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":""},
    {"name":"Stirnband","genus":"neutrum","numerus":"singular","adjektiv":"","präfix":"","suffix":""},
    {"name":"Strickjacke","genus":"femininum","numerus":"singular","adjektiv":"","präfix":"","suffix":""},
    {"name":"Strumpfhose","genus":"femininum","numerus":"singular","adjektiv":"","präfix":"","suffix":""},
    {"name":"Toga","genus":"femininum","numerus":"singular","adjektiv":"","präfix":"","suffix":""},
    {"name":"Topfhelm","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":""},
    {"name":"Trenchcoat","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":""},
    {"name":"Tuch","genus":"neutrum","numerus":"singular","adjektiv":"","präfix":"","suffix":""},
    {"name":"Tunika","genus":"femininum","numerus":"singular","adjektiv":"","präfix":"","suffix":""},
    {"name":"Umhang","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":""},
    {"name":"Unterarmschutz","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":""},
    {"name":"Unterrock","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":""},
    {"name":"Wams","genus":"maskulinum","numerus":"singular","adjektiv":"","präfix":"","suffix":""},
    {"name":"Weste","genus":"femininum","numerus":"singular","adjektiv":"","präfix":"","suffix":""},
    {"name":"Zwangsjacke","genus":"femininum","numerus":"singular","präfix":"","suffix":""}
   ];
   const kleidungsstückeSingularData = getRandomText(kleidungsstückeSingular);
   const kleidungsstückeSingularName = kleidungsstückeSingularData.name;
   const kleidungsstückeSingularGeschlecht = kleidungsstückeSingularData.genus;
   const kleidungsstückeSingularAnzahl = kleidungsstückeSingularData.numerus;
   const kleidungsstückeSingularAdjektiv = kleidungsstückeSingularData.adjektiv;
   const kleidungsstückeSingularPräfix = kleidungsstückeSingularData.präfix;
   const kleidungsstückeSingularSuffix = kleidungsstückeSingularData.suffix;