const völkerSingular = [
    ...(document.getElementById("checkboxDrachenlanze").checked ? [
     ] : []),
     ...(document.getElementById("checkboxEberron").checked ? [
     ] : []),
     ...(document.getElementById("checkboxExandria").checked ? [
     ] : []),
     ...(document.getElementById("checkboxGreyhawk").checked ? [
     ] : []),
     ...(document.getElementById("checkboxRavenloft").checked ? [
     ] : []),
     ...(document.getElementById("checkboxRavnica").checked ? [
     ] : []),
     ...(document.getElementById("checkboxSpelljammer").checked ? [
     ] : []),
     ...(document.getElementById("checkboxStrixhaven").checked ? [
     ] : []),
     ...(document.getElementById("checkboxTheros").checked ? [
     ] : []),	
     //...(document.getElementById("checkboxVergesseneReiche").checked ? [
     //] : []),
     {"name":"Aarakocra","genus":"maskulinum","numerus":"Singular","adjektiv":"","präfix":"","suffix":""},
     {"name":"Astralelf","genus":"maskulinum","numerus":"Singular","adjektiv":"","präfix":"","suffix":""},
     {"name":"Autognom","genus":"maskulinum","numerus":"Singular","adjektiv":"","präfix":"","suffix":""},
     {"name":"Beschützer-Aasimar","genus":"maskulinum","numerus":"Singular","adjektiv":"","präfix":"","suffix":""},
     {"name":"Blasself","genus":"maskulinum","numerus":"Singular","adjektiv":"","präfix":"","suffix":""},
     {"name":"Bullywug","genus":"maskulinum","numerus":"Singular","adjektiv":"","präfix":"","suffix":""},
     {"name":"Drachgenblütige","genus":"maskulinum","numerus":"Singular","adjektiv":"chromatische","präfix":"","suffix":""},
     {"name":"Dämmerungself","genus":"maskulinum","numerus":"Singular","adjektiv":"","präfix":"","suffix":""},
     {"name":"Derros","genus":"maskulinum","numerus":"Singular","adjektiv":"","präfix":"","suffix":""},
     {"name":"Dhampir","genus":"maskulinum","numerus":"Singular","adjektiv":"","präfix":"","suffix":""},
     {"name":" Drachenblütige","genus":"maskulinum","numerus":"Singular","adjektiv":"drachlingsblütige","präfix":"","suffix":""},
     {"name":"Dunkelelf","genus":"maskulinum","numerus":"Singular","adjektiv":"","präfix":"","suffix":""},
     {"name":"Dunkelzwerg","genus":"maskulinum","numerus":"Singular","adjektiv":"","präfix":"","suffix":""},
     {"name":"Echsenmensch","genus":"maskulinum","numerus":"Singular","adjektiv":"","präfix":"","suffix":""},
     {"name":"Edelstein-Drachenblütige","genus":"maskulinum","numerus":"Singular","adjektiv":"","präfix":"","suffix":""},
     {"name":"Eladrin","genus":"maskulinum","numerus":"Singular","adjektiv":"","präfix":"","suffix":""},
     {"name":"Erd-Genasi","genus":"maskulinum","numerus":"Singular","adjektiv":"","präfix":"","suffix":""},
     {"name":"Fee","genus":"femininum","numerus":"Singular","adjektiv":"","präfix":"","suffix":""},
     {"name":"Felsengnom","genus":"maskulinum","numerus":"Singular","adjektiv":"","präfix":"","suffix":""},
     {"name":"Feuer-Genasi","genus":"maskulinum","numerus":"Singular","adjektiv":"","präfix":"","suffix":""},
     {"name":"Feuermolch","genus":"maskulinum","numerus":"Singular","adjektiv":"","präfix":"","suffix":""},
     {"name":"Firbolg","genus":"maskulinum","numerus":"Singular","adjektiv":"","präfix":"","suffix":""},
     {"name":"Flinkläufer-Wandler","genus":"maskulinum","numerus":"Singular","adjektiv":"","präfix":"","suffix":""},
     {"name":"Gebirgszwerg","genus":"maskulinum","numerus":"Singular","adjektiv":"","präfix":"","suffix":""},
     {"name":"Gefallene Aasimar","genus":"maskulinum","numerus":"Singular","adjektiv":"","präfix":"","suffix":""},
     {"name":"Geißel-Aasimar","genus":"maskulinum","numerus":"Singular","adjektiv":"","präfix":"","suffix":""},
     {"name":"Geisterwaisen-Halbling","genus":"maskulinum","numerus":"Singular","adjektiv":"","präfix":"","suffix":""},
     {"name":"Giff","genus":"maskulinum","numerus":"Singular","adjektiv":"","präfix":"","suffix":""},
     {"name":"Githyanki","genus":"maskulinum","numerus":"Singular","adjektiv":"","präfix":"","suffix":""},
     {"name":"Githzerai","genus":"maskulinum","numerus":"Singular","adjektiv":"","präfix":"","suffix":""},
     {"name":"Gnoll","genus":"maskulinum","numerus":"Singular","adjektiv":"","präfix":"","suffix":""},
     {"name":"Goblin","genus":"maskulinum","numerus":"Singular","adjektiv":"","präfix":"","suffix":""},
     {"name":"Goliath","genus":"maskulinum","numerus":"Singular","adjektiv":"","präfix":"","suffix":""},
     {"name":"Grimlock","genus":"maskulinum","numerus":"Singular","adjektiv":"","präfix":"","suffix":""},
     {"name":"Grottenschrat","genus":"maskulinum","numerus":"Singular","adjektiv":"","präfix":"","suffix":""},
     {"name":"Grung","genus":"maskulinum","numerus":"Singular","adjektiv":"","präfix":"","suffix":""},
     {"name":"Hadozee","genus":"maskulinum","numerus":"Singular","adjektiv":"","präfix":"","suffix":""},
     {"name":"Halbdrache","genus":"maskulinum","numerus":"Singular","adjektiv":"","präfix":"","suffix":""},
     {"name":"Halbelf","genus":"maskulinum","numerus":"Singular","adjektiv":"","präfix":"","suffix":""},
     {"name":"Halbork","genus":"maskulinum","numerus":"Singular","adjektiv":"","präfix":"","suffix":""},
     {"name":"Harengon","genus":"maskulinum","numerus":"Singular","adjektiv":"","präfix":"","suffix":""},
     {"name":"Hexenblütige","genus":"maskulinum","numerus":"Singular","adjektiv":"","präfix":"","suffix":""},
     {"name":"Hobgoblin","genus":"maskulinum","numerus":"Singular","adjektiv":"","präfix":"","suffix":""},
     {"name":"Hochelf","genus":"maskulinum","numerus":"Singular","adjektiv":"","präfix":"","suffix":""},
     {"name":"Hügelzwerg","genus":"maskulinum","numerus":"Singular","adjektiv":"","präfix":"","suffix":""},
     {"name":"Kalashtar","genus":"maskulinum","numerus":"Singular","adjektiv":"","präfix":"","suffix":""},
     {"name":"Kender","genus":"maskulinum","numerus":"Singular","adjektiv":"","präfix":"","suffix":""},
     {"name":"Kenku","genus":"maskulinum","numerus":"Singular","adjektiv":"","präfix":"","suffix":""},
     {"name":"Kobold","genus":"maskulinum","numerus":"Singular","adjektiv":"","präfix":"","suffix":""},
     {"name":"Kraul","genus":"maskulinum","numerus":"Singular","adjektiv":"","präfix":"","suffix":""},
     {"name":"Kriegsgeschmiedete","genus":"maskulinum","numerus":"Singular","adjektiv":"","präfix":"","suffix":""},
     {"name":"Kua-Toa","genus":"maskulinum","numerus":"Singular","adjektiv":"","präfix":"","suffix":""},
     {"name":"Langzahn-Wandler","genus":"maskulinum","numerus":"Singular","adjektiv":"","präfix":"","suffix":""},
     {"name":"Lavakind","genus":"neutrum","numerus":"Singular","adjektiv":"","präfix":"","suffix":""},
     {"name":"Leichtfuß-Halbling","genus":"maskulinum","numerus":"Singular","adjektiv":"","präfix":"","suffix":""},
     {"name":"Leonid","genus":"maskulinum","numerus":"Singular","adjektiv":"","präfix":"","suffix":""},
     {"name":"Locathah","genus":"maskulinum","numerus":"Singular","adjektiv":"","präfix":"","suffix":""},
     {"name":"Lotusden-Halbling","genus":"maskulinum","numerus":"Singular","adjektiv":"","präfix":"","suffix":""},
     {"name":"Loxodon","genus":"maskulinum","numerus":"Singular","adjektiv":"","präfix":"","suffix":""},
     {"name":"Luft-Genasi","genus":"maskulinum","numerus":"Singular","adjektiv":"","präfix":"","suffix":""},
     {"name":"Lykanthrop","genus":"maskulinum","numerus":"Singular","adjektiv":"","präfix":"","suffix":""},
     {"name":"Mazer","genus":"maskulinum","numerus":"Singular","adjektiv":"","präfix":"","suffix":""},
     {"name":"Meereself","genus":"maskulinum","numerus":"Singular","adjektiv":"","präfix":"","suffix":""},
     {"name":"Meervolk","genus":"neutrum","numerus":"Singular","adjektiv":"","präfix":"","suffix":""},
     {"name":"Mensch","genus":"maskulinum","numerus":"Singular","adjektiv":"","präfix":"","suffix":""},
     {"name":"Drachenblütige","genus":"maskulinum","numerus":"Singular","adjektiv":"metallische","präfix":"","suffix":""},
     {"name":"Minotaur","genus":"maskulinum","numerus":"Singular","adjektiv":"","präfix":"","suffix":""},
     {"name":"Mischlingsvolk","genus":"maskulinum","numerus":"Singular","adjektiv":"","präfix":"","suffix":""},
     {"name":"Nagpa","genus":"maskulinum","numerus":"Singular","adjektiv":"","präfix":"","suffix":""},
     {"name":"Nilbog","genus":"maskulinum","numerus":"Singular","adjektiv":"","präfix":"","suffix":""},
     {"name":"Ork","genus":"maskulinum","numerus":"Singular","adjektiv":"","präfix":"","suffix":""},
     {"name":"Orog","genus":"maskulinum","numerus":"Singular","adjektiv":"","präfix":"","suffix":""},
     {"name":"Plasmoid","genus":"maskulinum","numerus":"Singular","adjektiv":"","präfix":"","suffix":""},
     {"name":"Quaggoth","genus":"maskulinum","numerus":"Singular","adjektiv":"","präfix":"","suffix":""},
     {"name":"Ravenit-Drachenblütige","genus":"maskulinum","numerus":"Singular","adjektiv":"","präfix":"","suffix":""},
     {"name":"Sahuagin","genus":"maskulinum","numerus":"Singular","adjektiv":"","präfix":"","suffix":""},
     {"name":"Satyr","genus":"maskulinum","numerus":"Singular","adjektiv":"","präfix":"","suffix":""},
     {"name":"Saurianer","genus":"maskulinum","numerus":"Singular","adjektiv":"","präfix":"","suffix":""},
     {"name":"Shadar-Kai","genus":"maskulinum","numerus":"Singular","adjektiv":"","präfix":"","suffix":""},
     {"name":"Simic-Hybrid","genus":"maskulinum","numerus":"Singular","adjektiv":"","präfix":"","suffix":""},
     {"name":"Halbling","genus":"maskulinum","numerus":"Singular","adjektiv":"stämmige","präfix":"","suffix":""},
     {"name":"Tabaxi","genus":"maskulinum","numerus":"Singular","adjektiv":"","präfix":"","suffix":""},
     {"name":"Thri-Kreen","genus":"maskulinum","numerus":"Singular","adjektiv":"","präfix":"","suffix":""},
     {"name":"Tiefengnom","genus":"maskulinum","numerus":"Singular","adjektiv":"","präfix":"","suffix":""},
     {"name":"Tiefling","genus":"maskulinum","numerus":"Singular","adjektiv":"","präfix":"","suffix":""},
     {"name":"Tierhaut-Wandler","genus":"maskulinum","numerus":"Singular","adjektiv":"","präfix":"","suffix":""},
     {"name":"Tortle","genus":"maskulinum","numerus":"Singular","adjektiv":"","präfix":"","suffix":""},
     {"name":"Triton","genus":"maskulinum","numerus":"Singular","adjektiv":"","präfix":"","suffix":""},
     {"name":"Troglodyt","genus":"maskulinum","numerus":"Singular","adjektiv":"","präfix":"","suffix":""},
     {"name":"Uhle","genus":"maskulinum","numerus":"Singular","adjektiv":"","präfix":"","suffix":""},
     {"name":"Vedalken","genus":"maskulinum","numerus":"Singular","adjektiv":"","präfix":"","suffix":""},
     {"name":"Verdan","genus":"maskulinum","numerus":"Singular","adjektiv":"","präfix":"","suffix":""},
     {"name":"Waldelf","genus":"maskulinum","numerus":"Singular","adjektiv":"","präfix":"","suffix":""},
     {"name":"Waldgnom","genus":"maskulinum","numerus":"Singular","adjektiv":"","präfix":"","suffix":""},
     {"name":"Wasser-Genasi","genus":"maskulinum","numerus":"Singular","adjektiv":"","präfix":"","suffix":""},
     {"name":"Wechselbalg","genus":"maskulinum","numerus":"Singular","adjektiv":"","präfix":"","suffix":""},
     {"name":"Wiedergeborene","genus":"maskulinum","numerus":"Singular","adjektiv":"","präfix":"","suffix":""},
     {"name":"Wildläufer-Wandler","genus":"maskulinum","numerus":"Singular","adjektiv":"","präfix":"","suffix":""},
     {"name":"Yuan-Ti","genus":"maskulinum","numerus":"Singular","adjektiv":"","präfix":"","suffix":""},
     {"name":"Zentaur","genus":"maskulinum","numerus":"Singular","adjektiv":"","präfix":"","suffix":""}
    ];
   
    const völkerSingularData = getRandomText(völkerSingular);
    const völkerSingularName = völkerSingularData.name;
    const völkerSingularGeschlecht = völkerSingularData.genus;
    const völkerSingularAnzahl = völkerSingularData.numerus;
    const völkerSingularAdjektiv = völkerSingularData.adjektiv;
    const völkerSingularPräfix = völkerSingularData.präfix;
    const völkerSingularSuffix = völkerSingularData.suffix;