const völkerPlural = [
    ...(document.getElementById("checkboxDrachenlanze").checked ? [
     {"name":"Kender","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    ] : []),
    ...(document.getElementById("checkboxEberron").checked ? [					
     {"name":"Flinkläufer-Wandler","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
     {"name":"Kalashtar","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
     {"name":"Kriegsgeschmiedete","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
     {"name":"Langzahn-Wandler","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
     {"name":"Tierhaut-Wandler","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
     {"name":"Wechselbälger","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
     {"name":"Wildläufer-Wandler","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},					
    ] : []),
    ...(document.getElementById("checkboxExandria").checked ? [
     {"name":"Blasselfen","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
     {"name":"Lotusden-Halblinge","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
     {"name":"Ravenit-Drachenblütige","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
     {"name":"Drachenblütige","genus":"maskulinum","numerus":"plural","adjektiv":"drachlingsblütige","präfix":"","suffix":""},
    ] : []),
    ...(document.getElementById("checkboxGreyhawk").checked ? [
    ] : []),
    ...(document.getElementById("checkboxRavenloft").checked ? [
     {"name":"Dämmerungselfen","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
     {"name":"Dhampire","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
     {"name":"Hexenblütige","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
     {"name":"Mischlingsvölker","genus":"neutrum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
     {"name":"Wiedergeborenen","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    ] : []),
    ...(document.getElementById("checkboxRavnica").checked ? [
     {"name":"Simic-Hybride","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
     {"name":"Vedalken","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    ] : []),
    ...(document.getElementById("checkboxSpelljammer").checked ? [
     {"name":"Astralelfen","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
     {"name":"Autognome","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
     {"name":"Giff","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
     {"name":"Hadozee","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
     {"name":"Plasmoide","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
     {"name":"Thri-Kreen","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    ] : []),
    ...(document.getElementById("checkboxStrixhaven").checked ? [
     {"name":"Uhlen","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    ] : []),
    ...(document.getElementById("checkboxTheros").checked ? [
     {"name":"Leonide","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    ] : []),	
    ...(document.getElementById("checkboxVergesseneReiche").checked ? [
    ] : []),
    {"name":"Aarakocra","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},				
    {"name":"Beschützer-Aasimar","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Bullywugs","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Drachgenblütige","genus":"maskulinum","numerus":"plural","adjektiv":"chromatische","präfix":"","suffix":""},				
    {"name":"Derros","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},	
    {"name":"Dunkelelfen","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Dunkelzwerge","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Echsenmenschen","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Edelstein-Drachenblütige","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Eladrin","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Erd-Genasi","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Feen","genus":"femininum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Felsengnome","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Feuer-Genasi","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Feuermolche","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Firbolg","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},				
    {"name":"Gebirgszwerge","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Aasimar","genus":"maskulinum","numerus":"plural","adjektiv":"gefallene","präfix":"","suffix":""},
    {"name":"Geißel-Aasimar","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Geisterwaisen-Halblinge","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},				
    {"name":"Githyanki","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Githzerai","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Gnolle","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Goblins","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Goliaths","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Grimlocks","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Grottenschrate","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Grung","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},				
    {"name":"Halbdrachen","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Halbelfen","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Halborks","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Harengon","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Hobgoblins","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Hochelfen","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Hügelzwerge","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},				
    {"name":"Kenkus","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Kobolde","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Kraul","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Kua-Toas","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Lavakinder","genus":"neutrum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Halblinge","genus":"maskulinum","numerus":"plural","adjektiv":"leichtfüßige","präfix":"","suffix":""},				
    {"name":"Locathah","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},				
    {"name":"Luft-Genasi","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Lykanthrope","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Mazer","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Meereselfen","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Meervölker","genus":"neutrum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Menschen","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Drachenblütige","genus":"maskulinum","numerus":"plural","adjektiv":"metallischen","präfix":"","suffix":""},
    {"name":"Minotauren","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},				
    {"name":"Nagpa","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Nilbogs","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Orks","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Orog","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},				
    {"name":"Quaggoth","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},				
    {"name":"Sahuagine","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Satyren","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Saurianer","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Shadar-Kai","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},				
    {"name":"Halblinge","genus":"maskulinum","numerus":"plural","adjektiv":"stämmige","präfix":"","suffix":""},
    {"name":"Tabaxi","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},				
    {"name":"Tiefengnome","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Tieflinge","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},				
    {"name":"Tortle","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Tritons","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Troglodyten","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},		
    {"name":"Verdan","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Waldelfen","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Waldgnome","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Wasser-Genasi","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},				
    {"name":"Yuan-Ti","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""},
    {"name":"Zentauren","genus":"maskulinum","numerus":"plural","adjektiv":"","präfix":"","suffix":""}
   ];
  
   const völkerPluralData = getRandomText(völkerPlural);
   const völkerPluralName = völkerPluralData.name;
   const völkerPluralGeschlecht = völkerPluralData.genus;
   const völkerPluralAnzahl = völkerPluralData.numerus;
   const völkerPluralAdjektiv = völkerPluralData.adjektiv;
   const völkerPluralPräfix = völkerPluralData.präfix;
   const völkerPluralSuffix = völkerPluralData.suffix;